Repository SeisNN/SeisNN, pull requests merged in 2021-06, with the labels that each got.

#63 Continues data
  scripts/00_read_CVA_waveform.py
  scripts/continues_data.py
  seisnn/io.py
  seisnn/model/trainer.py
  seisnn/plot.py
Labels: enhancement

#70 update base image to tf2.5.0
  README.md
  docker/Dockerfile.dev
Labels: docker

#85 Docker
  .github/workflows/docker_image_dev.yml
  docker/Dockerfile.dev
  requirements.txt
  requirements_dev.txt
  setup.py
Labels: dependencies, docker

#86 [skip ci] get seisnn version matched by pypi
  README.md
  setup.py
Labels: dependencies

#87 add pypi upload github action
  .github/workflows/pypi_upload.yml
Labels: CI/CD
